### ISSUE TITLE
serve command just stalls on erroneous management command

### ISSUE THREAD

**Issue by tschale** [django-hurricane/django-hurricane#60]
I used `serve` with `--command 'collectstatic noinput'`, which should be `--command 'collectstatic --noinput'`. The management commands raises the expected error, after that nothing happens. I would expect `serve` to exit when a management command raises an error.

**Comment by vvvityaaa** [comment]
What is happening in this case is that the http server is stopped, but the probe server is still running in the main loop. This is an intended behaviour in this case.

**Comment by Schille** [comment]
I think a failing `--command ` should stop Hurricane entirely. What do you say @tschale ?

**Comment by tschale** [comment]
The current behavior means that a pod running hurricane in K8s won't become alive and ready, correct? Which would be the same if we change the behavior so that hurricane stops when a `--command` fails, correct?
I mainly stumbled upon this when executing hurricane in a local virtualenv, which is not the main use case. But I'm in favor of letting hurricane stop entirely when a `--command` or another flag fails (I think I also had this behavior when the static-dir wasn't already created and `--static` fails as the dir couldn't be automatically created).

**Comment by vvvityaaa** [comment]
@tschale yes, this logic was with a thought, that a probe server should send back 400-th error, when any command fails. Otherwise, it will be just not available, which is also okay, I think.

**Comment by Schille** [comment]
@vvvityaaa Sure.

**Comment by elmcrest** [comment]
good evening everybody,
I just stumbled upon this and while exploring things some questions appeared.

please correct me if I'm wrong.
usually a pod is running somewhere in a k8s cluster and the python (single threaded) process is running with two asyncio servers in the event loop.
here the issue appeared because only the probe server survived since django's default behavior is to exit on startup errors like failed migrations, missing settings, etc.
If that's the case I'd probably agree with intended behavior as vvvityaaa said. A running probe server could still provide value to the cluster - I could imagine at least logging/notifications. For example the probe server reports an error to "somewhere" which could be instantly better than "hangs in crash loop" as the state of the pod. On top, if the probe server lives, python lives, the pod might still live, too. We could access it via attached shell and explore things if needed...

I can't verify those ideas right now so bear with me in case I'm talking nonsense :)

Anyways, nice project!
